# Passwörter mit bcrypt gehasht:
# python -c "from passlib.hash import bcrypt; print(bcrypt.hash('geheim'))"

users:
  - username: lehrer01
    password_hash: "$2b$12$oK3VKqm5UJo/iEQv2iInR.nCUA3jBrZwu7v7dLvmQIovz1dZtiEl2"
    role: teacher
    grade: null

  - username: schueler10a
    password_hash: "$2b$12$/9DdLzVyejpZ6KJBopnYZubL.saVp.X0zOjhPUtLpa9tDLime0GrS"
    role: student
    grade: "10a"

  - username: admin
    password_hash: "$2b$12$j42wD/P9FYGN/7XhfbTVtuqP.tRwIk8DU1XNK6wOGZLqQwyvT5XaS"
    role: admin
    grade: null
