"""initial schema

Revision ID: 0001
Revises:
Create Date: 2024-01-01 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subjects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("min_grade", sa.Integer(), nullable=True),
        sa.Column("max_grade", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True, server_default="0"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "assistants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True, server_default="'draft'"),
        sa.Column("force_cost_display", sa.Boolean(), nullable=True, server_default="false"),
        sa.Column("created_by_pseudonym", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            ondelete="SET NULL",
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'disabled', 'archived')",
            name="check_assistant_status",
        ),
    )
    op.create_table(
        "conversations",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text("gen_random_uuid()")),
        sa.Column("pseudonym", sa.String(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=True),
        sa.Column("assistant_id", sa.Integer(), nullable=True),
        sa.Column("system_prompt_snapshot", sa.String(), nullable=True),
        sa.Column("total_cost_usd", sa.Numeric(precision=10, scale=6), nullable=True, server_default="0"),
        sa.Column("last_message_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
            ondelete="SET NULL",
        ),
    )
    op.create_index("idx_conversations_pseudonym", "conversations", ["pseudonym"], unique=False)
    op.create_index("idx_conversations_last_message_at", "conversations", ["last_message_at"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False, server_default=sa.text("gen_random_uuid()")),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "role IN ('user', 'assistant')",
            name="check_message_role",
        ),
    )
    op.create_index("idx_messages_conversation_id", "messages", ["conversation_id"], unique=False)
    op.create_table(
        "user_preferences",
        sa.Column("pseudonym", sa.String(), nullable=False),
        sa.Column("preferences", postgresql.JSONB(), nullable=True, server_default="{}"),
        sa.PrimaryKeyConstraint("pseudonym"),
    )
    op.create_table(
        "pseudonym_audit",
        sa.Column("pseudonym", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("last_login_at", postgresql.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("revoked_all_before", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("pseudonym"),
    )
    op.create_table(
        "jwt_revocations",
        sa.Column("jti", sa.String(), nullable=False),
        sa.Column("pseudonym", sa.String(), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("jti"),
    )
    op.create_index("idx_jwt_revocations_pseudonym", "jwt_revocations", ["pseudonym"], unique=False)
    op.create_index("idx_jwt_revocations_expires_at", "jwt_revocations", ["expires_at"], unique=False)
    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("eur_usd_rate", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("effective_from", postgresql.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "source IN ('ECB', 'manual')",
            name="check_exchange_rate_source",
        ),
    )
    op.create_index("idx_exchange_rates_effective_from", "exchange_rates", ["effective_from"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_exchange_rates_effective_from", table_name="exchange_rates")
    op.drop_table("exchange_rates")
    op.drop_index("idx_jwt_revocations_expires_at", table_name="jwt_revocations")
    op.drop_index("idx_jwt_revocations_pseudonym", table_name="jwt_revocations")
    op.drop_table("jwt_revocations")
    op.drop_table("pseudonym_audit")
    op.drop_table("user_preferences")
    op.drop_index("idx_messages_conversation_id", table_name="messages")
    op.drop_table("messages")
    op.drop_index("idx_conversations_last_message_at", table_name="conversations")
    op.drop_index("idx_conversations_pseudonym", table_name="conversations")
    op.drop_table("conversations")
    op.drop_table("assistants")
    op.drop_table("subjects")
    # ### end Alembic commands ###
